import { CalendarDays } from "lucide-react";
import { Avatar, Badge, GlassCard, Progress } from "../ui";

type Project = { name: string; description: string; progress: number; status: string; due: string; members: string[]; color: string };

export function ProjectCard({ project }: { project: Project }) {
  const isComplete = project.progress === 100;
  return <GlassCard className="group relative overflow-hidden p-5 transition-all duration-300 hover:border-white/[.2] sm:p-6"><div className="pointer-events-none absolute -right-16 -top-16 h-40 w-40 rounded-full bg-violet-600/12 blur-3xl transition-opacity duration-300 group-hover:bg-violet-500/20" /><div className="relative flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold tracking-tight text-white transition-colors group-hover:text-violet-200">{project.name}</h3><p className="mt-1 text-xs text-slate-500">{project.description}</p></div><Badge className={isComplete ? "border-emerald-400/25 bg-emerald-500/12 text-emerald-300" : "border-violet-400/25 bg-violet-500/12 text-violet-300"}>{project.status}</Badge></div><div className="relative mt-6"><div className="flex items-center justify-between text-xs"><span className="text-slate-500">Velocity Progress</span><span className="font-semibold text-white">{project.progress}%</span></div><div className="mt-2"><Progress value={project.progress} color={project.progress > 75 ? "bg-gradient-to-r from-emerald-400 to-teal-400" : "bg-gradient-to-r from-violet-400 to-violet-700"} /></div></div><div className="relative mt-6 flex items-center justify-between border-t border-white/[.06] pt-2"><div className="flex -space-x-2">{project.members.map((member) => <Avatar key={member} initials={member} className="h-7 w-7 border-2 border-[#111115] text-[9px]" />)}</div><div className="flex items-center gap-1.5 text-[11px] text-slate-500"><CalendarDays size={13} className="text-slate-600" /><span>{project.due}</span></div></div></GlassCard>;
}
