"use client";

import { Command, Menu, Search } from "lucide-react";
import { NotificationDropdown } from "../shared/NotificationDropdown";
import { ThemeToggle } from "../shared/ThemeToggle";

type NavbarProps = { onMenuClick: () => void };

export function Navbar({ onMenuClick }: NavbarProps) {
  return <header className="sticky top-4 z-30 mx-4 flex h-14 items-center justify-between gap-4 rounded-2xl border border-white/[.07] bg-[#111115]/80 px-3.5 shadow-[0_18px_45px_rgba(0,0,0,.32)] backdrop-blur-2xl sm:mx-6 lg:mx-10"><div className="flex max-w-xl flex-1 items-center gap-3"><button onClick={onMenuClick} aria-label="Toggle navigation" className="rounded-xl p-2 text-slate-400 transition-colors hover:bg-white/[.06] hover:text-white lg:hidden"><Menu size={19} /></button><div className="relative hidden w-full sm:block"><Search size={15} className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-500" /><input className="h-9 w-full rounded-xl border border-white/[.07] bg-white/[.03] pl-10 pr-14 text-xs text-slate-200 outline-none placeholder:text-slate-500 transition-all hover:border-white/[.14] focus:border-violet-400/60 focus:bg-white/[.05] focus:ring-4 focus:ring-violet-500/10" placeholder="Search projects, tasks, branches, AI actions..." /><div className="pointer-events-none absolute right-2.5 top-1/2 flex -translate-y-1/2 items-center gap-1 rounded-md border border-white/[.08] bg-white/[.04] px-1.5 py-0.5 text-[10px] font-medium text-slate-500"><Command size={10} /><span>K</span></div></div></div><div className="flex items-center gap-1 sm:gap-2"><div className="hidden xl:flex items-center gap-2 rounded-full border border-emerald-400/15 bg-emerald-500/[.08] px-3 py-1 text-[10px] font-medium text-emerald-300"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-400" />DevOS Cloud · Connected</div><NotificationDropdown /><ThemeToggle /><div className="relative ml-1 flex cursor-pointer items-center gap-2 rounded-xl border border-white/[.07] bg-white/[.025] p-1.5 pr-3 transition-colors hover:bg-white/[.06]"><div className="relative h-7 w-7 rounded-full border border-violet-400/30 bg-gradient-to-tr from-violet-600 to-indigo-600 p-0.5"><div className="flex h-full w-full items-center justify-center rounded-full bg-[#17171d] text-[10px] font-bold text-white">RL</div><span className="absolute bottom-0 right-0 h-2 w-2 rounded-full border-2 border-[#111115] bg-emerald-400" /></div><div className="hidden text-left md:block"><p className="text-[11px] font-semibold leading-tight text-white">Rishu Lohar</p><p className="text-[9px] leading-tight text-slate-500">Pro Member</p></div></div></div></header>;
}
